services:
  # MySQL Database
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp_network

  # WordPress
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    volumes:
      # Mount the entire WordPress directory for direct file management
      - ./wordpress:/var/www/html
      # Mount the plugin code directly into the WordPress plugins directory
      - ./wp-easy-staging:/var/www/html/wp-content/plugins/wp-easy-staging
      # Mount wp-content directory to persist changes
      - wp_content:/var/www/html/wp-content
    networks:
      - wp_network

  # phpMyAdmin (optional but helpful for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wp_network

volumes:
  db_data:
  wp_content:

networks:
  wp_network: 