name: Generate and Commit Plugin as a Zip file

on:
  push:
    branches:
      - commit-latest-zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Zip the repository
        run: |
          zip -r latest.zip . -x ".gitignore" ".github"

      - name: Commit latest.zip
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add latest.zip
          git commit -m "Update latest.zip" || echo "No changes to commit"
          git push origin ${{ github.ref }}